# Needs this to increase the R default time-out time (INLA is a big package so may break installation without this)
options(timeout=600)
install.packages("tidyverse")
install.packages("rmarkdown")
install.packages('tinytex')
tinytex::install_tinytex(force=TRUE)
install.packages('remotes')
install.packages('rjags')
install.packages("R2OpenBUGS")
install.packages("R2jags")
remotes::install_github("giabaio/bmhe_utils")
install.packages("survHE")
install.packages("BCEA")
remotes::install_github("giabaio/survHEhmc")
install.packages("INLA",repos=c(getOption("repos"),INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)
remotes::install_github("giabaio/survHEinla")

## xaringan-related 
remotes::install_github("yihui/xaringan",dependencies=TRUE)
remotes::install_github("gadenbuie/xaringanExtra",dependencies=TRUE)
remotes::install_github("jhelvy/renderthis",dependencies=TRUE)
remotes::install_github("mitchelloharawild/icons",dependencies=TRUE)
remotes::install_github("daqana/tikzDevice",dependencies=TRUE)
install.packages("knitr",dependencies=TRUE)
remotes::install_github("rstudio/htmltools",dependencies=TRUE)
remotes::install_github("haozhu233/kableExtra",dependencies=TRUE)
install.packages("fontawesome")
remotes::install_github("giabaio/slides")
remotes::install_github("ropensci/RefManageR",dependencies=TRUE)
remotes::install_github("hadley/emo",dependencies=TRUE)
remotes::install_github("rstudio/fontawesome/")

# utilities
remotes::install_github("Azure/Microsoft365R",dependencies=TRUE)
remotes::install_github("rstudio/blastula",dependencies=TRUE)
