install.packages("tidyverse")
install.packages("rmarkdown")
install.packages('rjags')
install.packages("R2OpenBUGS")
install.packages("R2jags")
install.packages("INLA",repos=c(getOption("repos"),INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)
remotes::install_github("giabaio/bmhe_utils")
remotes::install_github("giabaio/survHE",ref="devel")
remotes::install_github("giabaio/survHE",ref="inla")
remotes::install_github("giabaio/BCEA",ref="dev")
